### ISSUE TITLE
Problems on the F1 score

### ISSUE THREAD

**Issue by yueguangxichen** [jayavardhanr/End-to-end-Sequence-Labeling-via-Bi-directional-LSTM-CNNs-CRF-Tutorial#2]
I have run the program but I can't get the same F1 score as listed in the paper, it is far away from the best score,it's just 0.86

**Comment by jayavardhanr** [comment]
We did not tune the model to achieve the results mentioned in the paper. Additional hyperparameter tuning has to be performed to achieve better results. All the hyperparameters are defined in the notebook, you can play around with them to improve the performance.
